export const OPEN_FIRST_MODAL = 'OPEN_FIRST_MODAL';
export const OPEN_SECOND_MODAL = 'OPEN_SECOND_MODAL';
export const CLOSE_FIRST_MODAL = 'CLOSE_FIRST_MODAL';
export const CLOSE_SECOND_MODAL = 'CLOSE_SECOND_MODAL';